### ISSUE TITLE
Small bug in method get_body_data() for EmailMessage in models.py?

### ISSUE THREAD

**Issue by yellowcap** [RyanBalfanz/django-sendgrid#63]
In the method `get_body_data()` in [sendgrid/models.py, line 269](https://github.com/RyanBalfanz/django-sendgrid/blob/develop/sendgrid/models.py#L269) I think `return self.subject.data` should probably be replaced with `return self.body.data`.

**Comment by RyanBalfanz** [comment]
Thanks, @yellowcap!
